name: 'datamodeling'
version: '0.1'

profile: 'default'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "logs"

models:
  datamodeling:
    raw:
      +schema: "{{ env_var('RAW_SCHEMA') }}"
    staging:
      +schema: "{{ env_var('STAGING_SCHEMA') }}"
    marts:
      +schema: "{{ env_var('MART_SCHEMA') }}"